// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC59G7unDuGDDTBI2TktYWVeV_LyA3aE58',
    appId: '1:287958448438:web:419a8bdef43eb14bb69b97',
    messagingSenderId: '287958448438',
    projectId: 'sp-grocerph',
    authDomain: 'sp-grocerph.firebaseapp.com',
    storageBucket: 'sp-grocerph.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn0rWG3XTYa1oaT-OdsVD1_wn2Ew74l_s',
    appId: '1:287958448438:android:38a2a88bf1a98d0cb69b97',
    messagingSenderId: '287958448438',
    projectId: 'sp-grocerph',
    storageBucket: 'sp-grocerph.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ6kpNt9S2o9aQEZwqnHxNeLWzHLLGPhk',
    appId: '1:287958448438:ios:e1b7325ecdf6f0cbb69b97',
    messagingSenderId: '287958448438',
    projectId: 'sp-grocerph',
    storageBucket: 'sp-grocerph.firebasestorage.app',
    iosBundleId: 'com.example.grocerPh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ6kpNt9S2o9aQEZwqnHxNeLWzHLLGPhk',
    appId: '1:287958448438:ios:e1b7325ecdf6f0cbb69b97',
    messagingSenderId: '287958448438',
    projectId: 'sp-grocerph',
    storageBucket: 'sp-grocerph.firebasestorage.app',
    iosBundleId: 'com.example.grocerPh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC59G7unDuGDDTBI2TktYWVeV_LyA3aE58',
    appId: '1:287958448438:web:c801bec96a813035b69b97',
    messagingSenderId: '287958448438',
    projectId: 'sp-grocerph',
    authDomain: 'sp-grocerph.firebaseapp.com',
    storageBucket: 'sp-grocerph.firebasestorage.app',
  );
}